version: '3.8'

services:
  static-website:
    build: .
    container_name: user-management-website
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-website.rule=Host(`localhost`)"
      - "traefik.http.services.static-website.loadbalancer.server.port=80"

networks:
  web-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local
